// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqupreqdsslchdnwvixn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxdXByZXFkc3NsY2hkbnd2aXhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NzM3ODEsImV4cCI6MjA3MjQ0OTc4MX0.NCa1HQAx3jkK6mCvQBkrTFLQt9BPZsbad0UrX0o3GiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});